package MyApp::Schema::TestDatabase;

use strict;
use base qw/DBIx::Class::Schema::Loader/;

__PACKAGE__->loader_options(
    relationships => '1',
    use_moose => '1',
    col_collision_map => 'column_%s',
    use_namespaces => '1',
    components => ["InflateColumn::DateTime"],
);

=head1 NAME

MyApp::Schema::TestDatabase - L<DBIx::Class::Schema::Loader> class

=head1 SYNOPSIS

See L<MyApp>

=head1 DESCRIPTION

Dynamic L<DBIx::Class::Schema::Loader> schema for use in L<MyApp::Model::TestDatabase>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Daniel Torres

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

